name: test

on: [push, pull_request]

env:
  GOFLAGS: -mod=vendor
  GO111MODULE: on
  CONSUL_HTTP_TOKEN: master-token
  CONSUL_HTTP_ADDR: http://localhost:8500

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Unit tests
      run: |
        docker run -v $PWD:/src docker.mirror.hashicorp.services/bflad/tfproviderlint -S006 -S022 -S023 ./...
        make test
    - name: Vetting code
      run: make vet
  acceptance-test-ce:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Acceptance tests on Consul Community Edition
      run: |
        docker run --rm \
                  -d \
                  --name consul-test \
                  -v $PWD/consul_test.hcl:/consul_test.hcl:ro \
                  -p 8500:8500 \
                  docker.mirror.hashicorp.services/consul:latest consul agent -dev -config-file consul_test.hcl -client=0.0.0.0
        make testacc TESTARGS="-count=1"
        docker stop consul-test
  acceptance-test-ee:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Acceptance tests on Consul Enterprise Edition
      run: |
        docker run --rm \
                  -d \
                  --name consul-test \
                  -v $PWD/consul_test.hcl:/consul_test.hcl:ro \
                  -p 8500:8500 \
                  docker.mirror.hashicorp.services/hashicorp/consul-enterprise:latest consul agent -dev -config-file consul_test.hcl -client=0.0.0.0
        make testacc TESTARGS="-count=1"
        docker stop consul-test
  remote-acceptance-test-ce:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Remote datacenter tests on Consul Community Edition
      run: |
        docker run --rm \
                  -d \
                  --name consul-test-dc2 \
                  -v $PWD/consul_test_dc2.hcl:/consul_test_dc2.hcl:ro \
                  --net host \
                  docker.mirror.hashicorp.services/consul:latest consul agent -dev -config-file consul_test_dc2.hcl
        docker run --rm \
                  -d \
                  --name consul-test \
                  -v $PWD/consul_test.hcl:/consul_test.hcl:ro \
                  --net host \
                  docker.mirror.hashicorp.services/consul:latest consul agent -dev -config-file consul_test.hcl
        TEST_REMOTE_DATACENTER=1 make testacc TESTARGS="-count=1"
        docker stop consul-test consul-test-dc2
  remote-acceptance-test-ee:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Remote datacenter tests on Consul Enterprise Edition
      run: |
        docker run --rm \
                  -d \
                  --name consul-test-dc2 \
                  -v $PWD/consul_test_dc2.hcl:/consul_test_dc2.hcl:ro \
                  --net host \
                  docker.mirror.hashicorp.services/hashicorp/consul-enterprise:latest consul agent -dev -config-file consul_test_dc2.hcl
        docker run --rm \
                  -d \
                  --name consul-test \
                  -v $PWD/consul_test.hcl:/consul_test.hcl:ro \
                  --net host \
                  docker.mirror.hashicorp.services/hashicorp/consul-enterprise:latest consul agent -dev -config-file consul_test.hcl
        TEST_REMOTE_DATACENTER=1 make testacc TESTARGS="-count=1"
        docker stop consul-test consul-test-dc2
